@startuml Hotel

class Usuario {
  - nome: String
  - login: String
  - senha: String
  - listaTelefone: List<Telefone>
  - endereco: Endereco
  - reservas: List<Reserva>
}

class Telefone {
  - codigoArea: String
  - numero: String
}

class Endereco {
  - estado: String
  - cidade: String
  - quadra: String
  - rua: String
  - numero: String
}

class Reserva {
  - dataInicio: LocalDate
  - dataFinal: LocalDate
  - pagamento: Pagamento
}

class Pagamento {
  - tipoPagamento: TipoPagamento
  - valor: double
}

class Quarto {
  - numero: int
  - tipo: TipoQuarto
  - preco: double
  - disponivel: Boolean
}

class QuartoDescricao {
  - descricao: String
  - quartoHotel: Quarto
}

enum TipoQuarto {
  SIMPLES,
  CASAL,
  LUXO,
  PRESIDENCIAL
}

enum TipoPagamento {
  CARTAO_CREDITO,
  CARTAO_DEBITO,
  DINHEIRO,
  TRANSFERENCIA
}

Usuario --o Telefone : 1..*
Usuario --o Endereco : 1
Usuario --o Reserva : 0..*
Reserva --o Quarto : 1
Reserva --o Usuario : 1
Reserva --o Pagamento : 0..1
Pagamento --o Reserva : 1
Quarto --o QuartoDescricao : 1..*
Quarto --o Reserva : 0..*
TipoQuarto -- Quarto : Contém
TipoPagamento -- Pagamento : Utiliza

@enduml
