@startuml

class Usuario {
  - id: Long
  - login: String
  - senha: String
  + construtor()
  + getters/setters()
}

class Endereco {
  + estado: String
  + cidade: String
  + quadra: String
  + rua: String
  + numero: String
}

class Telefone {
  + codigoArea: String
  + numero: String
}

class Quarto {
  - id: Long
  - numero: int
  - tipo: TipoQuarto
  - preco: double
  - disponivel: boolean
  + construtor()
  + getters/setters()
}

enum TipoQuarto {
  SINGLE
  DUPLO
  LUXO
  PRESIDENCIAL
}

class Reserva {
  - id: Long
  - usuario: Usuario
  - quarto: Quarto
  - dataInicio: LocalDate
  - dataFim: LocalDate
  + construtor()
  + getters/setters()
}

class Pagamento {
  - id: Long
  - tipo: TipoPagamento
  - valor: double
  + construtor()
  + getters/setters()
}

enum TipoPagamento {
  CARTAO_CREDITO
  CARTAO_DEBITO
  DINHEIRO
  TRANSFERENCIA
}

Usuario -- Reserva : Realiza
Quarto -- Reserva : ReservadoPor
Reserva -- Pagamento : Possui
Quarto --> TipoQuarto : tipo
Reserva --> TipoPagamento : tipo
Usuario "1" --> "0..*" Telefone : possui
Usuario "1" --> "1" Endereco : possui

@enduml
